/**
 * Universal Service Flow Framework
 * Config-driven step engine that determines booking flow based on service-type metadata.
 * Each service type is tagged with flow_type and behavioral flags that dynamically
 * produce the correct step sequence — eliminating incorrect flows like
 * AC Installation showing repair issue lists.
 */

// ─── TYPES ──────────────────────────────────────────────────────

export type BookingStepId =
  | "landing"
  | "service_type"
  | "issue"
  | "pricing_expectation"
  | "part_grade"
  | "service_mode"
  | "location"
  | "device_details"
  | "smart_diagnosis"
  | "diagnosis_summary"
  | "ac_install_addons"
  | "site_conditions"
  | "pricing"
  | "booking_protection"
  | "assignment"
  | "confirmation";

export type ServiceFlowType =
  | "repair"
  | "standard_service"
  | "installation"
  | "inspection_consultation"
  | "remote_digital";

export type BookingOutcome =
  | "direct_booking"
  | "inspection_booking"
  | "quote_request"
  | "remote_session_booking"
  | "pickup_request";

export type DispatchBehavior =
  | "instant"
  | "delayed"
  | "inspection_first"
  | "remote_allocation"
  | "manual_ops_review";

export type ServicePricingArchetype =
  | "fixed_price"
  | "starting_from"
  | "diagnostic_first"
  | "inspection_required";

export interface ServiceTypeConfig {
  /** Which universal flow type this service follows */
  flow_type: ServiceFlowType;
  /** Show issue/symptom selection step? */
  requires_issue_step: boolean;
  /** Show installation requirements builder (e.g., AC addons)? */
  requires_install_builder: boolean;
  /** Must inspection/site visit happen before work? */
  requires_inspection_first: boolean;
  /** Can this service be fulfilled remotely? */
  allows_remote_mode: boolean;
  /** Show access/site condition questions? */
  requires_access_conditions: boolean;
  /** Show part grade selection? */
  requires_part_grade: boolean;
  /** Encourage/require photo upload? */
  requires_photo_upload: boolean;
  /** Show property profile questions? */
  requires_property_profile: boolean;
  /** Show service mode selection? */
  requires_service_mode: boolean;
  /** Show smart diagnosis flow? */
  requires_smart_diagnosis: boolean;
  /** Show pricing/package selection? */
  requires_pricing_step: boolean;
  /** Pricing archetype for this specific service */
  pricing_archetype: ServicePricingArchetype;
  /** What the booking resolves to */
  booking_outcome: BookingOutcome;
  /** Dispatch behavior */
  dispatch_behavior: DispatchBehavior;
}

// ─── SERVICE TYPE CONFIGS ───────────────────────────────────────
// Key format: `${categoryCode}::${serviceTypeId}`

const SERVICE_TYPE_CONFIGS: Record<string, ServiceTypeConfig> = {
  // ═══ AC ═══════════════════════════════════════════════════════
  "AC::service": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "AC::deep_clean": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "AC::repair": {
    flow_type: "repair",
    requires_issue_step: true,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "AC::gas": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "AC::install": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: true,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "AC::relocation": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "starting_from",
    booking_outcome: "quote_request",
    dispatch_behavior: "delayed",
  },
  "AC::water_leak": {
    flow_type: "repair",
    requires_issue_step: true,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "AC::not_sure": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ CCTV ════════════════════════════════════════════════════
  "CCTV::new_install": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "CCTV::upgrade": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "CCTV::repair": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "CCTV::inspection": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "CCTV::not_sure": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: true,
    requires_pricing_step: false,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ IT ══════════════════════════════════════════════════════
  "IT::laptop_screen": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::laptop_battery": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::laptop_storage": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::laptop_motherboard": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::laptop_hinge": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::laptop_keyboard": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::laptop_overheating": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::desktop_power": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::desktop_motherboard": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::desktop_ram": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::desktop_gpu": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::desktop_psu": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::network": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::printer": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "IT::software": {
    flow_type: "remote_digital",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: true,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "remote_session_booking",
    dispatch_behavior: "remote_allocation",
  },
  "IT::data_recovery": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "pickup_request",
    dispatch_behavior: "delayed",
  },
  "IT::not_sure": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ MOBILE ══════════════════════════════════════════════════
  "MOBILE::screen": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: true,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "MOBILE::battery": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: true,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "MOBILE::charging": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: true,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "MOBILE::water": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: true,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "MOBILE::camera": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: true,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "MOBILE::software": {
    flow_type: "remote_digital",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: true,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "MOBILE::not_sure": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ CONSUMER ELECTRONICS ════════════════════════════════════
  "CONSUMER_ELEC::tv": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "CONSUMER_ELEC::washing": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "CONSUMER_ELEC::fridge": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "CONSUMER_ELEC::microwave": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "CONSUMER_ELEC::fan": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "CONSUMER_ELEC::other": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ SOLAR ═══════════════════════════════════════════════════
  "SOLAR::new_install": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "SOLAR::expand": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "SOLAR::maintenance": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "SOLAR::troubleshoot": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ SMART HOME / OFFICE ═════════════════════════════════════
  "SMART_HOME_OFFICE::security": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "SMART_HOME_OFFICE::automation": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "SMART_HOME_OFFICE::energy": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "SMART_HOME_OFFICE::office": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },

  // ═══ COPIER ══════════════════════════════════════════════════
  "COPIER::paper_jam": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::print_quality": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::not_printing": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::wifi_setup": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::installation": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::toner_drum": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::roller_service": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::copier_service": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: true,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "COPIER::not_sure": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: false,
    requires_service_mode: true,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ PRINT SUPPLIES ══════════════════════════════════════════
  "PRINT_SUPPLIES::toner_order": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "delayed",
  },
  "PRINT_SUPPLIES::ink_order": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "delayed",
  },
  "PRINT_SUPPLIES::drum_unit": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "delayed",
  },
  "PRINT_SUPPLIES::ribbon": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "delayed",
  },
  "PRINT_SUPPLIES::thermal_roll": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "delayed",
  },
  "PRINT_SUPPLIES::maintenance_kit": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: false,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "delayed",
  },

  // ═══ ELECTRICAL ══════════════════════════════════════════════
  "ELECTRICAL::socket": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "ELECTRICAL::circuit_breaker": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "ELECTRICAL::rewiring": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "ELECTRICAL::lighting": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "ELECTRICAL::fan": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "ELECTRICAL::surge": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "ELECTRICAL::not_sure": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ PLUMBING ════════════════════════════════════════════════
  "PLUMBING::leak": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "PLUMBING::pump": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "PLUMBING::tank": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "PLUMBING::bathroom": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "PLUMBING::kitchen": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "PLUMBING::hot_water": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "PLUMBING::not_sure": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ NETWORK ═════════════════════════════════════════════════
  "NETWORK::wifi_setup": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "NETWORK::mesh": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "NETWORK::office_lan": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "NETWORK::troubleshoot": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: true,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: true,
    requires_pricing_step: true,
    pricing_archetype: "diagnostic_first",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "NETWORK::cabling": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "NETWORK::speed": {
    flow_type: "standard_service",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: true,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },

  // ═══ HOME SECURITY ═══════════════════════════════════════════
  "HOME_SECURITY::doorbell": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "HOME_SECURITY::smart_lock": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "starting_from",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "HOME_SECURITY::alarm": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "HOME_SECURITY::intercom": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "HOME_SECURITY::gate": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },

  // ═══ POWER BACKUP ════════════════════════════════════════════
  "POWER_BACKUP::ups": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "POWER_BACKUP::inverter": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "POWER_BACKUP::generator": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "POWER_BACKUP::battery": {
    flow_type: "repair",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "POWER_BACKUP::solar_battery": {
    flow_type: "inspection_consultation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },

  // ═══ APPLIANCE INSTALLATION ══════════════════════════════════
  "APPLIANCE_INSTALL::ac_install": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: true,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
  "APPLIANCE_INSTALL::washing": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "APPLIANCE_INSTALL::tv_mount": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "APPLIANCE_INSTALL::water_heater": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: false,
    allows_remote_mode: false,
    requires_access_conditions: false,
    requires_part_grade: false,
    requires_photo_upload: false,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: true,
    pricing_archetype: "fixed_price",
    booking_outcome: "direct_booking",
    dispatch_behavior: "instant",
  },
  "APPLIANCE_INSTALL::kitchen": {
    flow_type: "installation",
    requires_issue_step: false,
    requires_install_builder: false,
    requires_inspection_first: true,
    allows_remote_mode: false,
    requires_access_conditions: true,
    requires_part_grade: false,
    requires_photo_upload: true,
    requires_property_profile: true,
    requires_service_mode: false,
    requires_smart_diagnosis: false,
    requires_pricing_step: false,
    pricing_archetype: "inspection_required",
    booking_outcome: "inspection_booking",
    dispatch_behavior: "inspection_first",
  },
};

// ─── DEFAULT CONFIG ─────────────────────────────────────────────
// Fallback for any service type not explicitly configured
const DEFAULT_CONFIG: ServiceTypeConfig = {
  flow_type: "repair",
  requires_issue_step: false,
  requires_install_builder: false,
  requires_inspection_first: false,
  allows_remote_mode: false,
  requires_access_conditions: false,
  requires_part_grade: false,
  requires_photo_upload: false,
  requires_property_profile: false,
  requires_service_mode: true,
  requires_smart_diagnosis: false,
  requires_pricing_step: true,
  pricing_archetype: "diagnostic_first",
  booking_outcome: "direct_booking",
  dispatch_behavior: "instant",
};

// ─── PUBLIC API ─────────────────────────────────────────────────

/**
 * Get the config for a specific service type.
 */
export function getServiceTypeConfig(
  categoryCode: string,
  serviceTypeId: string
): ServiceTypeConfig {
  const key = `${categoryCode}::${serviceTypeId}`;
  return SERVICE_TYPE_CONFIGS[key] || DEFAULT_CONFIG;
}

/**
 * Build the step sequence from config flags.
 * This is the core engine that derives steps dynamically.
 */
function buildStepsFromConfig(
  config: ServiceTypeConfig,
  context: {
    serviceModeId?: string;
    hasDiagBlock?: boolean;
    hasIssueSelectors?: boolean;
    hasSiteConditions?: boolean;
    hasServiceModes?: boolean;
  }
): BookingStepId[] {
  const steps: BookingStepId[] = ["landing", "service_type"];

  // 1. Issue step — only if config says so AND category has issue selectors
  if (config.requires_issue_step && context.hasIssueSelectors) {
    steps.push("issue");
  }

  // 2. Pricing expectation — always shown to explain the pricing model
  steps.push("pricing_expectation");

  // 3. Part grade — only for repair flows that need it
  if (config.requires_part_grade) {
    steps.push("part_grade");
  }

  // 4. Service mode — only if config requires it AND category has modes defined
  if (config.requires_service_mode && context.hasServiceModes) {
    steps.push("service_mode");
  }

  // 5. Location — skip for remote and drop_off modes
  const skipLocation =
    config.allows_remote_mode ||
    context.serviceModeId === "remote" ||
    context.serviceModeId === "drop_off";
  if (!skipLocation) {
    steps.push("location");
  }

  // 6. Device details — always present (filtered by showForServiceTypes in component)
  steps.push("device_details");

  // 7. Smart diagnosis — only if config says so AND diagnostic block exists
  if (config.requires_smart_diagnosis && context.hasDiagBlock) {
    steps.push("smart_diagnosis", "diagnosis_summary");
  }

  // 8. Install builder (AC addons) — only for installation flows that need it
  if (config.requires_install_builder) {
    steps.push("ac_install_addons");
  }

  // 9. Site conditions — only if config requires access conditions AND category has them
  //    Skip for remote mode
  if (config.requires_access_conditions && context.hasSiteConditions) {
    if (context.serviceModeId !== "remote") {
      steps.push("site_conditions");
    }
  }

  // 10. Pricing/package selection — skip for inspection-first and quote-required flows
  if (config.requires_pricing_step) {
    steps.push("pricing");
  }

  // 11. Booking protection — always
  steps.push("booking_protection");

  // 12. Assignment — always
  steps.push("assignment");

  // 13. Confirmation — always
  steps.push("confirmation");

  return steps;
}

/**
 * Get the step sequence for a given category + service type.
 * Before a service type is selected, returns just ["landing", "service_type"].
 */
export function getServiceSteps(
  categoryCode: string,
  serviceTypeId: string | undefined,
  context?: {
    serviceModeId?: string;
    hasDiagBlock?: boolean;
    hasIssueSelectors?: boolean;
    hasSiteConditions?: boolean;
    hasServiceModes?: boolean;
  }
): BookingStepId[] {
  // Before service type is selected, only show landing + service type
  if (!serviceTypeId) {
    return ["landing", "service_type"];
  }

  const config = getServiceTypeConfig(categoryCode, serviceTypeId);
  return buildStepsFromConfig(config, context || {});
}
