import type { Campaign, CampaignType, TrustBadge } from '@/types/campaign';

/**
 * Fallback / seeded campaigns shown when no remote campaigns are available.
 * These are static, operationally safe, and trust-led.
 */

const c = (
  overrides: Partial<Campaign> & Pick<Campaign, 'id' | 'campaign_name' | 'campaign_type' | 'title'>
): Campaign => ({
  subtitle: undefined,
  body: undefined,
  cta_label: 'Learn More',
  cta_deep_link: '/',
  image_url: undefined,
  mobile_image_url: undefined,
  language: 'en',
  category_ids: [],
  zones: [],
  audience_type: 'all',
  priority: 50,
  active_days: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
  required_supply_threshold: 1,
  minimum_supply_confidence: 0,
  slot_strategy: 'top_hero_slot',
  booking_state_rules: {},
  user_segment_rules: {},
  suppression_rules: {},
  fatigue_rules: {},
  approval_status: 'approved',
  trust_badges: [],
  status: 'active',
  created_at: new Date().toISOString(),
  ...overrides,
});

export const FALLBACK_CAMPAIGNS: Campaign[] = [
  c({
    id: 'fallback-ac-demand',
    campaign_name: 'AC Seasonal Demand',
    campaign_type: 'seasonal_demand',
    title: 'AC service demand rising this week',
    subtitle: 'Book verified AC technicians before slots fill up',
    cta_label: 'Book AC Service',
    cta_deep_link: '/book/ac',
    category_ids: ['AC'],
    priority: 80,
    slot_strategy: 'top_hero_slot',
    trust_badges: ['verified_partner', 'transparent_pricing'],
    urgency_tag: 'High Demand',
  }),
  c({
    id: 'fallback-mobile-repair',
    campaign_name: 'Mobile Screen Repair',
    campaign_type: 'hero_promotion',
    title: 'Need mobile screen repair?',
    subtitle: 'Verified partner available nearby — transparent pricing',
    cta_label: 'Fix My Screen',
    cta_deep_link: '/book/mobile',
    category_ids: ['MOBILE'],
    priority: 75,
    slot_strategy: 'top_hero_slot',
    trust_badges: ['verified_partner', 'genuine_parts', 'warranty_backed'],
  }),
  c({
    id: 'fallback-inspection-first',
    campaign_name: 'Inspection First',
    campaign_type: 'trust_reassurance',
    title: "Not sure what's wrong?",
    subtitle: 'Get an inspection-first diagnosis — no obligation to repair',
    cta_label: 'Book Inspection',
    cta_deep_link: '/diagnose',
    priority: 70,
    slot_strategy: 'trust_slot',
    trust_badges: ['inspection_first', 'transparent_pricing', 'diagnostic_protected'],
  }),
  c({
    id: 'fallback-sme-it',
    campaign_name: 'SME IT Support',
    campaign_type: 'sme_business',
    title: 'SME IT support slots open tomorrow',
    subtitle: 'Verified technicians for your business IT needs',
    cta_label: 'Book IT Support',
    cta_deep_link: '/book/it',
    category_ids: ['IT'],
    audience_type: 'business',
    priority: 60,
    slot_strategy: 'business_slot',
    trust_badges: ['business_ready', 'verified_partner'],
  }),
  c({
    id: 'fallback-solar',
    campaign_name: 'Solar Site Visits',
    campaign_type: 'hero_promotion',
    title: 'Solar site visits now available',
    subtitle: 'Free consultation for home & commercial solar solutions',
    cta_label: 'Schedule Visit',
    cta_deep_link: '/book/solar',
    category_ids: ['SOLAR'],
    priority: 55,
    slot_strategy: 'trending_slot',
    trust_badges: ['sri_lanka_aligned', 'structured_tracking'],
  }),
  c({
    id: 'fallback-warranty',
    campaign_name: 'Warranty Repairs',
    campaign_type: 'warranty_assurance',
    title: 'Warranty-backed electronics repairs',
    subtitle: 'Genuine parts • Transparent process • Service guarantee',
    cta_label: 'Book Repair',
    cta_deep_link: '/book/consumer-electronics',
    category_ids: ['CONSUMER_ELEC'],
    priority: 50,
    slot_strategy: 'trust_slot',
    trust_badges: ['warranty_backed', 'genuine_parts', 'transparent_pricing'],
  }),
  c({
    id: 'fallback-cctv',
    campaign_name: 'CCTV for Business',
    campaign_type: 'sme_business',
    title: 'Book verified CCTV support for your office',
    subtitle: 'Installation, repair & maintenance by verified partners',
    cta_label: 'Get CCTV Help',
    cta_deep_link: '/book/cctv',
    category_ids: ['CCTV'],
    priority: 45,
    slot_strategy: 'business_slot',
    trust_badges: ['verified_partner', 'business_ready'],
  }),
  c({
    id: 'fallback-trust-general',
    campaign_name: 'Trust General',
    campaign_type: 'trust_reassurance',
    title: 'Every LankaFix partner is verified',
    subtitle: 'Background checked • Skill verified • Tracked service',
    priority: 30,
    slot_strategy: 'trust_slot',
    trust_badges: ['verified_partner', 'structured_tracking', 'data_safe'],
  }),
  c({
    id: 'fallback-education-tips',
    campaign_name: 'Service Tips',
    campaign_type: 'education_info',
    title: 'Know before you book',
    subtitle: 'Quick tips to get the best service experience on LankaFix',
    cta_label: 'Read Tips',
    cta_deep_link: '/tips',
    priority: 25,
    slot_strategy: 'education_slot',
  }),
  c({
    id: 'fallback-power-backup',
    campaign_name: 'Power Backup Solutions',
    campaign_type: 'hero_promotion',
    title: 'Power backup consultation available',
    subtitle: 'Protect your home & office from outages',
    cta_label: 'Get Consultation',
    cta_deep_link: '/book/power-backup',
    category_ids: ['POWER_BACKUP'],
    priority: 40,
    slot_strategy: 'trending_slot',
    trust_badges: ['sri_lanka_aligned', 'ceb_compliant'],
  }),
];

/** User-context recovery campaign templates */
export const CONTEXT_CAMPAIGNS = {
  pendingBooking: c({
    id: 'ctx-pending-booking',
    campaign_name: 'Continue Booking',
    campaign_type: 'user_recovery',
    title: 'Continue your booking',
    subtitle: 'Your service request is waiting — pick up where you left off',
    cta_label: 'Continue',
    cta_deep_link: '/bookings',
    priority: 95,
    slot_strategy: 'recovery_slot',
  }),
  pendingQuote: c({
    id: 'ctx-pending-quote',
    campaign_name: 'Quote Waiting',
    campaign_type: 'pending_quote',
    title: 'Your quote is waiting',
    subtitle: 'A technician has submitted a quote — review and approve',
    cta_label: 'View Quote',
    cta_deep_link: '/bookings',
    priority: 98,
    slot_strategy: 'recovery_slot',
  }),
  abandonedBooking: c({
    id: 'ctx-abandoned',
    campaign_name: 'Abandoned Recovery',
    campaign_type: 'user_recovery',
    title: 'Need help deciding?',
    subtitle: 'Inspection-first available — no commitment, just clarity',
    cta_label: 'Get Inspection',
    cta_deep_link: '/diagnose',
    priority: 90,
    slot_strategy: 'recovery_slot',
    trust_badges: ['inspection_first'],
  }),
} as const;

export const TRUST_BADGE_LABELS: Record<TrustBadge, string> = {
  verified_partner: 'Verified Partner',
  transparent_pricing: 'Transparent Pricing',
  warranty_backed: 'Warranty Backed',
  inspection_first: 'Inspection First',
  sri_lanka_aligned: 'Sri Lanka Aligned',
  business_ready: 'Business Ready',
  data_safe: 'Data Safe',
  genuine_parts: 'Genuine Parts',
  structured_tracking: 'Tracked Service',
  ceb_compliant: 'CEB Compliant',
  diagnostic_protected: 'Diagnostic Protected',
};

export const CAMPAIGN_TYPE_ICONS: Record<CampaignType, string> = {
  hero_promotion: '🔥',
  trust_reassurance: '🛡️',
  seasonal_demand: '📈',
  user_recovery: '🔄',
  pending_quote: '📋',
  education_info: '💡',
  nearby_technicians: '📍',
  sme_business: '🏢',
  warranty_assurance: '✅',
  subscription_amc: '📅',
  partner_spotlight: '⭐',
  emergency_alert: '🚨',
};
